name: Dispatch Event

on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch wasm-languages-updated event
    runs-on: ubuntu-22.04
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          repository: ${{ secrets.DEST_REPO }}
          event-type: wasm-languages-updated
          client-payload: '{"event_type": "wasm-languages-updated", "sha": "${{ github.sha }}"}'